name: Demo Workflow

on: 
  push:
    branches:
      - main

jobs:
  print: 
    runs-on: ubuntu-latest 
    steps:
      - name: Print to console
        run: echo "Hello Github Actions!"
      - name: Print a few lines
        run: |
          echo 1 line
          echo 2 line 
          echo 3 line
